[package]
name = "linear-predictive-coding"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16"
num-traits = "0.2"
ndarray-inverse = { git = "https://github.com/oligamiq/ndarray-inverse"}
